### ISSUE TITLE
MoveCursor 'descending diagonal' not working in AWSDS

### ISSUE THREAD

**Issue by derycck** [4strid/mouse-control.autohotkey#6] opened 2022-05-22 03:01 UTC
Moving descending diagonal left/right in AWSD position in 'Normal quick mode' does not work.

On other hand, moving descending diagonal down left/right in 'HJKL' position in 'Normal quick mode' works fine.

**Comment by CoopCodes** [comment] 2022-10-10 08:35
Hey! I'm also having this problem, on one of my pc's it works, but on my laptop it doesn't.

**Comment by CoopCodes** [comment] 2023-02-01 01:28
I think its a problem with the keyboard, because some of my keyboards work, and some don't.

**Comment by 4strid** [comment] 2023-07-22 16:47
oh yeah i think i see what this might be . I can't reproduce it , but I think it's , some keyboards only have enough wires to send 2 key presses at the same time , and quick-diagonal-down would require registering three keys at once . my advice @ this time would just be to switch into normal mode if you need to move diagonally . closing this for now , alas ,

**Closed by 4strid** 2023-07-22 16:47 UTC
